import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='h-full bg-[#111827] overflow-auto'>
          <div className='mx-auto max-w-screen-xl h-full'>{children}</div>
        </main>
      </body>
    </html>
  );
}
